openapi: 3.0.0
info:
  title: serviziBancariAPI
  description: È l'API Restful offerta dal *fornitore dei servizi bancari* che rende
    accessibile la capability di generazione di un codice di pagamento con certi parametri
    e di ricevere dati relativi al pagamento di un cliente.
  version: "1.0"
servers:
- url: https://stoplight.io/mocks/soseng-unibo/soseng-project-documentation/7424070
  description: testing
paths:
  /paymentdata:
    post:
      tags:
      - Risorse
      summary: Ricevi dati di pagamento
      description: È la risorsa che permette al cliente intenzionato ad acquistare
        un'offerta di inviare al fornitore dei servizi bancari il pagamento corrispondente.
      operationId: post_paymentdata
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/paymentaDataBody'
            examples:
              Esempio:
                value:
                  card_number: 1234123412341234
                  expiration:
                    month: 11
                    year: 2024
                  CVC: 123
                  circuit: maestro
                  transaction:
                    id: abcd12
                    date: "2020-03-05, 12:06 CET"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - apikey: []
      x-openapi-router-controller: swagger_server.controllers.risorse_controller
  /link:
    post:
      tags:
      - Risorse
      summary: Genera link di pagamento
      description: "È la risorsa che, a fronte di una richiesta HTTP nella cui intestazione\
        \ vi è un `token` identificativo valido, restituisce un codice di pagamento\
        \ relativo all'offerta specificata."
      operationId: get_link
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/link_body'
            examples:
              Esempio:
                value:
                  amount:
                    value: 100
                    currency: €
                  offer_code: abcd123
                  airline: ryanair
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                Esempio:
                  value:
                    link: 123ayshgga
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - apikey: []
      x-openapi-router-controller: swagger_server.controllers.risorse_controller
  /registration:
    post:
      tags:
      - Risorse
      summary: Registra un nuovo utente
      description: È la risorsa che permette a chi intende interagire con il fornitore
        dei servizi bancari di ottenere l'APIKey per poter essere identificato e autorizzato.
      operationId: post_registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Maps.v1_Credentials'
            examples:
              Esempio:
                value:
                  username: Mario
                  password: 1245a5a
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              examples:
                Esempio:
                  value:
                    token: bWFnZ2llOnN1bW1lcnM=
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      x-openapi-router-controller: swagger_server.controllers.risorse_controller
components:
  schemas:
    Maps.v1_Credentials:
      title: credentials
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    paymentdata_expiration:
      type: object
      properties:
        month:
          type: integer
        year:
          type: integer
    paymentdata_transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
    paymentaDataBody:
      title: paymentaDataBody
      type: object
      properties:
        card_number:
          type: integer
        expiration:
          $ref: '#/components/schemas/paymentdata_expiration'
        CVC:
          type: integer
        circuit:
          type: string
        transaction:
          $ref: '#/components/schemas/paymentdata_transaction'
    link_amount:
      type: object
      properties:
        value:
          type: number
        currency:
          type: string
    link_body:
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/link_amount'
        offer_code:
          type: string
          description: "Codice dell'offerta che il cliente intende acquistare: in\
            \ dettaglio, questo codice non è quello identificante la coppia offerta\
            \ - cliente, bensì è quello assegnato, in principio, all'offerta dalla\
            \ compagnia aerea che l'ha attivata, ancor prima di comunicarla ad ACMESky.\n\
            \nQuando il fornitore dei servizi bancari inoltrerà la quota del pagamento\
            \ del cliente alla compagnia aerea, le invierà anche questo codice per\
            \ comunicarle l'offerta di cui le sta inviando il pagamento."
        airline:
          type: string
          description: "Compagnia aerea che ha attivato l'offerta per il cui pagamento\
            \ si chiede la generazione del link: servirà al fornitore dei servizi\
            \ bancari per inoltrarle la quota spettante."
    inline_response_200:
      type: object
      properties:
        link:
          type: string
      example:
        link: link
    inline_response_200_1:
      type: object
      properties:
        token:
          type: string
      example:
        token: token
  parameters:
    AuthorizationAPIKey:
      name: AuthorizationAPIKey
      in: header
      description: Il valore deve essere il token che il cliente ha ricevuto durante
        la registrazione.
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    apikey:
      type: apiKey
      description: Questo schema di sicurezza è stato impostato al fine di permettere
        esclusivamente ad ACMESky di richiedere alla banca la generazione del link
        di pagamento per una certa offerta.
      name: apikey
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_apikey

